name: clinic_match_app
description: Find your clinic nearby

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^8.0.0
  google_sign_in: ^5.4.3
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^14.2.1
  firebase_performance: ^0.9.0+10
  firebase_remote_config: ^3.0.9
  flutter_linkify: ^5.0.2
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^1.1.6
  flutter_snake_navigationbar: ^0.6.1
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.8.0
  mobx: ^2.1.3
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  timelines: ^0.1.0
  url_launcher: ^6.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/pngs/
    - assets/gifs/
    - assets/svgs/