// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgdzNKeNc0BpytDwh8w6LK-hdwplFZWY',
    appId: '1:298505808948:android:59c68abe1bfc56d824ee61',
    messagingSenderId: '298505808948',
    projectId: 'clinic-match-dev',
    storageBucket: 'clinic-match-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcY6C2qbGd9lu9T_rpuPxevYQVwiHIqSk',
    appId: '1:298505808948:ios:aae1b8c04c6b31a624ee61',
    messagingSenderId: '298505808948',
    projectId: 'clinic-match-dev',
    storageBucket: 'clinic-match-dev.appspot.com',
    androidClientId: '298505808948-ja2k4hka61pbtotbpvna9gkccsgo7qkj.apps.googleusercontent.com',
    iosClientId: '298505808948-tabqb7qmqnq42t98lr837sgt5ej8sc19.apps.googleusercontent.com',
    iosBundleId: 'com.clinicmatch.clinicMatchApp',
  );
}
